### ISSUE TITLE
Compile with java 1.7 please

### ISSUE THREAD

**Issue by madtomic** [PaperSpigot/PaperDocs#8]
http://pastebin.com/ub6BzJw2

Can you please compile it with java 1.7 as I can't get java 1.8 on Debian, there is no official java 1.8 yet.

**Comment by Zbob750** [comment]
No. There are repositories to get java 8 from on Debian. We aren't dropping the language version just because Debian's packages are ancient. http://www.webupd8.org/2014/03/how-to-install-oracle-java-8-in-debian.html

**Comment by madtomic** [comment]
Thank you for that. I found that early on but never attempt to install that Java but all is well now.
